credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "github-credentials-devhalos"
              description: "Github Credentials - devhalos"
              scope: GLOBAL
              username: "${GITHUB_USERNAME_DEVHALOS}"
              password: "${GITHUB_PASSWORD_DEVHALOS}"
          - usernamePassword:
              id: "github-credentials-token-jobs-devhalos"
              description: "Github Credentials Token Job - devhalos"
              scope: GLOBAL
              username: "devhalo21028"
              password: "${GITHUB_TOKEN_JOBS_DEVHALOS}"
          - usernamePassword:
              id: "github-credentials-token-devhalos"
              description: "Github Credentials Token - devhalos"
              scope: GLOBAL
              username: "${GITHUB_USERNAME_DEVHALOS}"
              password: "${GITHUB_TOKEN_DEVHALOS}"
          - string:
              id: "github-token-devhalos"
              description: "Github Token - devhalos"
              scope: GLOBAL
              secret: "${GITHUB_TOKEN_DEVHALOS}"
          - string:
              id: "sonarqube-token-devhalos"
              description: "Sonarqube Token - devhalos"
              scope: GLOBAL
              secret: "${SONARQUBE_TOKEN_DEVHALOS}"
