jenkins:
  systemMessage: "Jenkins - Nihil"
  numExecutors: 4
  mode: NORMAL
  clouds:
    - ecs:
        allowedOverrides: "inheritFrom,label,memory,cpu,image"
        credentialsId: ""
        cluster: ${JENKINS_ECS_CLUSTER_NAME}
        name: "fargate-cloud"
        regionName: ${JENKINS_ECS_CLUSTER_REGION}
        retentionTimeout: 10
        jenkinsUrl: "http://localhost:8080"
        templates:
          - assignPublicIp: true
            cpu: "512"
            image: "jenkins/inbound-agent"
            label: "ecs-fargate-agent-nihil-jenkins"
            launchType: "FARGATE"
            memory: 0
            memoryReservation: 1024
            networkMode: "awsvpc"
            privileged: false
            remoteFSRoot: "/home/jenkins"
            securityGroups: ${JENKINS_ECS_AGENT_SECURITY_GROUPS}
            sharedMemorySize: 0
            subnets: ${JENKINS_ECS_SUBNETS}
            templateName: "ecs-fargate-agent-nihil-jenkins"
            uniqueRemoteFSRoot: false