version: '3.3'

services:
  jenkins:
    image: nihil-jenkins:${JENKINS_IMAGE_TAG}
    container_name: nihil-jenkins
    deploy:
      restart_policy:
        condition: any
        window: 60s
        delay: 5s
        max_attempts: 5
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - JENKINS_ADMIN_USERNAME=${JENKINS_ADMIN_USERNAME}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_ECS_AGENT_NAME=${JENKINS_ECS_AGENT_NAME}
      - JENKINS_ECS_TUNNEL=${JENKINS_ECS_TUNNEL}
      - JENKINS_ECS_TASK_EXECUTION_ROLE=${JENKINS_ECS_TASK_EXECUTION_ROLE}
      - JENKINS_ECS_CLUSTER_NAME=${JENKINS_ECS_CLUSTER_NAME}
      - JENKINS_ECS_CLUSTER_REGION=${JENKINS_ECS_CLUSTER_REGION}
      - JENKINS_ECS_SUBNETS=${JENKINS_ECS_SUBNETS}
      - JENKINS_ECS_AGENT_SECURITY_GROUPS=${JENKINS_ECS_AGENT_SECURITY_GROUPS}
      - JENKINS_ECS_AWSLOGS_GROUP=${JENKINS_ECS_AWSLOGS_GROUP}
      - JENKINS_ECS_AWSLOGS_REGION=${JENKINS_ECS_AWSLOGS_REGION}
      - JENKINS_ECS_AWSLOGS_STREAM_PREFIX=${JENKINS_ECS_AWSLOGS_STREAM_PREFIX}
      - JENKINS_ECS_CPU=${JENKINS_ECS_CPU}
      - JENKINS_ECS_MEMORY_RESERVATION=${JENKINS_ECS_MEMORY_RESERVATION}
      - GITHUB_USERNAME_DEVHALOS=${GITHUB_USERNAME_DEVHALOS}
      - GITHUB_PASSWORD_DEVHALOS=${GITHUB_PASSWORD_DEVHALOS}
      - GITHUB_TOKEN_JOBS_DEVHALOS=${GITHUB_TOKEN_JOBS_DEVHALOS}
      - GITHUB_TOKEN_DEVHALOS=${GITHUB_TOKEN_DEVHALOS}
      - SONARQUBE_TOKEN_DEVHALOS=${SONARQUBE_TOKEN_DEVHALOS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nihil-jenkins-data:/var/jenkins_home
    networks:
      nihil-net:
        aliases:
          - nihil-jenkins

volumes:
  nihil-jenkins-data:
    external: true

networks:
  nihil-net:
    external: true
